import './RotateBanner.scss';

const RotateBanner = () => (
  <div className="RotateBannerWrapper ania">
    <p>
      • SOFTWARE ENGINEER • STRATEGIC THINKER • CREATEIVE PROBLEM SOLVER • SOFTWARE ENGINEER • STRATEGIC THINKER •
      CREATEIVE PROBLEM SOLVER • SOFTWARE ENGINEER • STRATEGIC THINKER • CREATEIVE PROBLEM SOLVER&nbsp;
    </p>
    <p>
      • SOFTWARE ENGINEER • STRATEGIC THINKER • CREATEIVE PROBLEM SOLVER • SOFTWARE ENGINEER • STRATEGIC THINKER •
      CREATEIVE PROBLEM SOLVER • SOFTWARE ENGINEER • STRATEGIC THINKER • CREATEIVE PROBLEM SOLVER
    </p>
  </div>
);

export default RotateBanner;
